version: "3"

services:
    pavlov:
        image: thelastbilly/pavlov:17062021
        container_name: pavlov
        volumes:
            - "./logs:/steam/pavlovserver/Pavlov/Saved/Logs"
            - "./config:/steam/pavlovserver/Pavlov/Saved/Config"
        environment: 
            - UID=1000
            - GID=1000
